# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["<oss@fastly.com>"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 2
name = "Default starter for Rust"
